version: '3.8'

services:
  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # MySQL Shard 1 Master
  mysql-shard1-master:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    command: --server-id=1 --log-bin=mysql-bin

  # MySQL Shard 1 Replica 1
  mysql-shard1-replica1:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    command: --server-id=2

  # MySQL Shard 1 Replica 2
  mysql-shard1-replica2:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    command: --server-id=3

  # MySQL Shard 2 Master
  mysql-shard2-master:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    command: --server-id=4 --log-bin=mysql-bin

  # MySQL Shard 2 Replica 1
  mysql-shard2-replica1:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    command: --server-id=5

  # MySQL Shard 2 Replica 2
  mysql-shard2-replica2:
    image: mysql:8.0
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    command: --server-id=6

  # Read Replica
  mysql-read-replica:
    image: mysql:8.0
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    command: --server-id=7