version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  mysql-shard-1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shard1
    ports:
      - "3306:3306"
    volumes:
      - mysql1_data:/var/lib/mysql

  mysql-shard-2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shard2
    ports:
      - "3307:3306"
    volumes:
      - mysql2_data:/var/lib/mysql

  mysql-shard-3:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shard3
    ports:
      - "3308:3306"
    volumes:
      - mysql3_data:/var/lib/mysql

  mysql-read:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: readdb
    ports:
      - "3309:3306"  # Fixed this from 3306 to 3309
    volumes:
      - mysql_read_data:/var/lib/mysql

  testing-api:
    build: ./testing-api
    ports:
      - "3000:3000"
    depends_on: [kafka, mysql-shard-1, mysql-shard-2, mysql-shard-3]
    environment:
      KAFKA_BROKERS: kafka:9092
      PRODUCER_SERVICE_URL: http://producer-service:8080

  producer-service:
    build: ./producer-service
    ports:
      - "8080:8080"
    depends_on: [kafka]
    environment:
      KAFKA_BROKERS: kafka:9092
      MYSQL_SHARD_1: mysql-shard-1:3306
      MYSQL_SHARD_2: mysql-shard-2:3306
      MYSQL_SHARD_3: mysql-shard-3:3306

  consumer-service:
    build: ./consumer-service
    depends_on: [kafka, mysql-shard-1, mysql-shard-2, mysql-shard-3]
    environment:
      KAFKA_BROKERS: kafka:9092
      MYSQL_SHARD_1: mysql-shard-1:3306
      MYSQL_SHARD_2: mysql-shard-2:3306
      MYSQL_SHARD_3: mysql-shard-3:3306

  cdc-service:
    build: ./cdc-service
    depends_on: [kafka, mysql-read]
    environment:
      KAFKA_BROKERS: kafka:9092
      MYSQL_READ: mysql-read:3306

volumes:
  mysql1_data:
  mysql2_data:
  mysql3_data:
  mysql_read_data: